sync

diff --git a/regress/sbin/iked/live/Makefile b/regress/sbin/iked/live/Makefile
--- a/regress/sbin/iked/live/Makefile
+++ b/regress/sbin/iked/live/Makefile
@@ -1,4 +1,4 @@
-#	$OpenBSD: Makefile,v 1.17 2020/09/10 20:40:18 tobhe Exp $
+#	$OpenBSD: Makefile,v 1.21 2020/09/13 11:48:10 tobhe Exp $
 
 # Copyright (c) 2020 Tobias Heider <tobhe@openbsd.org>
 #
@@ -32,7 +32,7 @@ regress:
 
 TEST_FLOWS = \
 	[ -z $$tmode ] && tmode=tunnel; \
-	success=false; \
+	_ret=1; \
 	count=0; \
 	while [[ $$count -le 3 ]]; do \
 		ipsecctlleft=`ssh ${LEFT_SSH} ipsecctl -sa`; \
@@ -52,14 +52,13 @@ TEST_FLOWS = \
 		if [[ -n "$$saleft_ltor" && -n "$$saleft_rtol" && \
 		     -n "$$saright_ltor" && -n "$$saright_rtol" && \
 		     -n "$$flowleft" && -n "$$flowright" ]]; then \
-			 success=true; \
+			 _ret=0; \
 			 break; \
 		fi; \
 		let count=$$count+1; \
 	done; \
-	if [[ "$$success" = false ]]; then \
-		echo "error: SAs not found:\n$$ipsecctlleft\n$$ipsecctlright"; \
-		exit 1; \
+	if [[ "$${_ret}" -ne 0 ]]; then \
+		echo "SAs not found:\n$$ipsecctlleft\n$$ipsecctlright"; \
 	fi
 
 TEST_PING = \
@@ -87,10 +86,10 @@ TEST_SINGLEIKESA = \
 		exit 1; \
 	fi
 
-SETUP_CONFIGS = \
+SETUP_CONFIG = \
+	if [[ -z "$$mode" ]]; then mode="active"; fi; \
 	authstr=""; \
 	if [[ "$$auth" = "psk" ]]; then \
-		psk=`openssl rand -hex 20`; \
 		authstr="psk $$psk"; \
 	fi; \
 	ipcomp=""; \
@@ -104,26 +103,39 @@ SETUP_CONFIGS = \
 	if [ "$$singleikesa" = true ]; then \
 		global="$${global}set enforcesingleikesa\n"; \
 	fi; \
-	echo "TMODE=\"$$tmode\"" > $@_left.conf; \
-	echo "LOCAL_ADDR=\"${LEFT_ADDR}\"" >> $@_left.conf; \
-	echo "PEER_ADDR=\"${RIGHT_ADDR}\"" >> $@_left.conf; \
-	echo "IPCOMP=\"$$ipcomp\"" >> $@_left.conf; \
-	echo "SRCID=\"$$leftid\"" >> $@_left.conf; \
-	echo "AUTH=\"$$authstr\"" >> $@_left.conf; \
-	echo "$$global" >> $@_left.conf; \
-	cat ${.CURDIR}/iked.in >> $@_left.conf; \
+	echo "MODE=\"$$mode\"" >> $@_$$side.conf; \
+	echo "TMODE=\"$$tmode\"" >> $@_$$side.conf; \
+	echo "LOCAL_ADDR=\"$$local\"" >> $@_$$side.conf; \
+	echo "PEER_ADDR=\"$$peer\"" >> $@_$$side.conf; \
+	echo "IPCOMP=\"$$ipcomp\"" >> $@_$$side.conf; \
+	echo "SRCID=\"$$srcid\"" >> $@_$$side.conf; \
+	echo "DSTID=\"$$dstid\"" >> $@_$$side.conf; \
+	echo "AUTH=\"$$authstr\"" >> $@_$$side.conf; \
+	echo "$$global" >> $@_$$side.conf; \
+	cat ${.CURDIR}/iked.in >> $@_$$side.conf
+
+DEPLOY_CONFIGS = \
 	chmod 0600 $@_left.conf; \
 	echo "cd /tmp\nput $@_left.conf test.conf" | sftp -q ${LEFT_SSH}; \
-	echo "TMODE=\"$$tmode\"" > $@_right.conf; \
-	echo "LOCAL_ADDR=\"${RIGHT_ADDR}\"" >> $@_right.conf; \
-	echo "PEER_ADDR=\"${LEFT_ADDR}\"" >> $@_right.conf; \
-	echo "IPCOMP=\"$$ipcomp\"" >> $@_right.conf; \
-	echo "SRCID=\"$$rightid\"" >> $@_right.conf; \
-	echo "AUTH=\"$$authstr\"" >> $@_right.conf; \
-	echo "$$global" >> $@_right.conf; \
-	cat ${.CURDIR}/iked.in >> $@_right.conf; \
 	chmod 0600 $@_right.conf; \
-	echo "cd /tmp\nput $@_right.conf test.conf" | sftp -q ${RIGHT_SSH}
+	echo "cd /tmp\nput $@_right.conf test.conf" | sftp -q ${RIGHT_SSH}; \
+	rm -f $@_left.conf $@_right.conf
+
+SETUP_CONFIGS = \
+	if [[ "$$auth" = "psk" ]]; then \
+		psk=`openssl rand -hex 20`; \
+	fi; \
+	side=left; \
+	srcid=$$leftid; \
+	local=${LEFT_ADDR}; \
+	peer=${RIGHT_ADDR}; \
+	    ${SETUP_CONFIG}; \
+	side=right; \
+	srcid=$$rightid; \
+	local=${RIGHT_ADDR}; \
+	peer=${LEFT_ADDR}; \
+	    ${SETUP_CONFIG}; \
+	${DEPLOY_CONFIGS}
 
 SETUP_SYSCTL = \
 	ssh ${LEFT_SSH} "sysctl $$sysctl"; \
@@ -225,14 +237,76 @@ run-ping-fail:
 REGRESS_TARGETS += run-cert-single-ca
 run-cert-single-ca:
 	@echo '======= $@ ========'
-	flowtype=esp;
 	leftid=left-from-ca-both; \
 	rightid=right-from-ca-both; \
 	    ${SETUP_CONFIGS}
 	${SETUP_START}
-	flowtype=esp; ${TEST_FLOWS}
-	${TEST_PING}; \
-	if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	flowtype=esp; ${TEST_FLOWS}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	${TEST_PING}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
+
+REGRESS_TARGETS += run-dstid-fail
+run-dstid-fail:
+	@echo '======= $@ ========'
+	leftid=left-from-ca-both; \
+	rightid=right-from-ca-both; \
+	    side=left; \
+	    srcid=$$leftid; \
+	    local=${LEFT_ADDR}; \
+	    peer=${RIGHT_ADDR}; \
+	    ${SETUP_CONFIG}; \
+	    side=right; \
+	    mode=passive; \
+	    srcid=$$rightid; \
+	    local=${RIGHT_ADDR}; \
+	    peer=${LEFT_ADDR}; \
+	    dstid="dstid invalid"; \
+	    ${SETUP_CONFIG}; \
+	    ${DEPLOY_CONFIGS}
+	${SETUP_START}
+	flowtype=esp; ${TEST_FLOWS}; if [[ $$_ret -ne 1 ]]; then exit 1; fi
+	${TEST_PING}; if [[ $$_ret -ne 1 ]]; then exit 1; fi
+
+REGRESS_TARGETS += run-dstid
+run-dstid:
+	@echo '======= $@ ========'
+	flowtype=esp;
+	leftid=left-from-ca-both; \
+	rightid=right-from-ca-both; \
+	    side=left; \
+	    srcid=$$leftid; \
+	    local=${LEFT_ADDR}; \
+	    peer=${RIGHT_ADDR}; \
+	    dstid="dstid $$rightid"; \
+	    ${SETUP_CONFIG}; \
+	    side=right; \
+	    srcid=$$rightid; \
+	    local=${RIGHT_ADDR}; \
+	    peer=${LEFT_ADDR}; \
+	    dstid="dstid $$leftid"; \
+	    ${SETUP_CONFIG}; \
+	    ${DEPLOY_CONFIGS}
+	${SETUP_START}
+	flowtype=esp; ${TEST_FLOWS}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	${TEST_PING}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
+
+REGRESS_TARGETS += run-dstid-multi
+run-dstid-multi:
+	@echo '======= $@ ========'
+	flowtype=esp;
+	leftid=left-from-ca-both; \
+	rightid=right-from-ca-both; \
+	    side=left; srcid=$$leftid; local=${LEFT_ADDR}; peer=${RIGHT_ADDR}; \
+	    dstid="dstid $$rightid"; \
+	    ${SETUP_CONFIG}; \
+	    side=right; mode=passive; srcid=$$rightid; local=${RIGHT_ADDR}; \
+	    peer=${LEFT_ADDR}; dstid="dstid $$leftid"; \
+	    ${SETUP_CONFIG}; \
+	    dstid="dstid roflol"; \
+	    ${SETUP_CONFIG}; \
+	    ${DEPLOY_CONFIGS}
+	${SETUP_START}
+	flowtype=esp; ${TEST_FLOWS}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	${TEST_PING}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
 
 REGRESS_TARGETS += run-cert-multi-ca
 run-cert-multi-ca:
@@ -242,9 +316,8 @@ run-cert-multi-ca:
 	rightid=right-from-ca-left; \
 	    ${SETUP_CONFIGS}
 	${SETUP_START}
-	flowtype=esp; ${TEST_FLOWS}
-	${TEST_PING}; \
-	if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	flowtype=esp; ${TEST_FLOWS}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	${TEST_PING}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
 
 REGRESS_TARGETS += run-cert-second-altname
 run-cert-second-altname:
@@ -254,9 +327,24 @@ run-cert-second-altname:
 	rightid=right-from-ca-both@openbsd.org; \
 	    ${SETUP_CONFIGS}
 	${SETUP_START}
-	flowtype=esp; ${TEST_FLOWS}
-	${TEST_PING}; \
-	if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	flowtype=esp; ${TEST_FLOWS}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	${TEST_PING}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
+
+REGRESS_TARGETS += run-psk-fail
+run-psk-fail:
+	@echo '======= $@ ========'
+	auth=psk; \
+	leftid=left-from-ca-both; \
+	rightid=right-from-ca-both; \
+	flowtype=esp; \
+	    side=left; psk=`openssl rand -hex 20`; \
+	    ${SETUP_CONFIG}; \
+	    side=right; psk=`openssl rand -hex 20`; \
+	    ${SETUP_CONFIG}; \
+	    ${DEPLOY_CONFIGS}
+	${SETUP_START}
+	flowtype=esp; ${TEST_FLOWS}; if [[ $$_ret -ne 1 ]]; then exit 1; fi
+	${TEST_PING}; if [[ $$_ret -ne 1 ]]; then exit 1; fi
 
 REGRESS_TARGETS += run-psk
 run-psk:
@@ -267,7 +355,8 @@ run-psk:
 	flowtype=esp; \
 	    ${SETUP_CONFIGS}
 	${SETUP_START}
-	flowtype=esp; ${TEST_FLOWS}
+	flowtype=esp; ${TEST_FLOWS}; \
+	if [[ $$_ret -ne 0 ]]; then exit 1; fi
 	${TEST_PING}; \
 	if [[ $$_ret -ne 0 ]]; then exit 1; fi
 
@@ -280,7 +369,8 @@ run-fragmentation:
 	rightid=right-from-ca-both; \
 	    ${SETUP_CONFIGS}
 	${SETUP_START}
-	flowtype=esp; ${TEST_FLOWS}
+	flowtype=esp; ${TEST_FLOWS}; \
+	if [[ $$_ret -ne 0 ]]; then exit 1; fi
 	${TEST_PING}; \
 	if [[ $$_ret -ne 0 ]]; then exit 1; fi
 
@@ -294,9 +384,8 @@ run-transport:
 	    ${SETUP_CONFIGS}
 	${SETUP_START}
 	tmode=transport; flowtype=esp; \
-	  ${TEST_FLOWS}
-	${TEST_PING}; \
-	if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	    ${TEST_FLOWS}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	${TEST_PING}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
 
 REGRESS_TARGETS += run-singleikesa
 run-singleikesa:
@@ -320,9 +409,8 @@ run-ipcomp:
 	sysctl="net.inet.ipcomp.enable=1"; \
 	    ${SETUP_SYSCTL}
 	${SETUP_START}
-	flowtype=ipcomp; ${TEST_FLOWS}
-	${TEST_PING}; \
-	if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	flowtype=ipcomp; ${TEST_FLOWS}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	${TEST_PING}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
 
 REGRESS_TARGETS += run-udpencap-port
 run-udpencap-port:
@@ -335,9 +423,8 @@ run-udpencap-port:
 	    ${SETUP_SYSCTL};
 	iked_flags=-p9999; \
 	    ${SETUP_START};
-	flowtype=esp; ${TEST_FLOWS}; \
-	    ${TEST_PING}; \
-	    if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	flowtype=esp; ${TEST_FLOWS}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
+	${TEST_PING}; if [[ $$_ret -ne 0 ]]; then exit 1; fi
 	sysctl="net.inet.esp.udpencap_port=4500"; \
 	    ${SETUP_SYSCTL};
 
